### PR TITLE
Update certbot-ocsp-fetcher

### PR DESCRIPTION
**Pull request by Seirdy**
certbot-ocsp-fetcher now can use a Systemd cache dir and service sandboxing.
See https://github.com/tomwassenberg/certbot-ocsp-fetcher/pull/19

### CODE REVIEW

**Comment by thestinger** [comment]
@Seirdy One of those paths isn't right (certbot part).

**Comment by Seirdy** [comment]
> @Seirdy One of those paths isn't right (certbot part).

The change was intentional. The script now checks for an envvar implicitly set by the `CacheDir` directive, which ends up pointing to `/var/certbot-ocsp-fetcher`.

**Comment by thestinger** [comment]
Isn't it /var/cache/ ?

**Comment by Seirdy** [comment]
On Wed Sep 7, 2022 at 11:38 PM PDT, Daniel Micay wrote:
> Isn't it /var/cache/ ?

Ahh...good catch. Fixed.

Also, forgot to commit the actual updated fetcher script.

**Comment by thestinger** [comment]
It's updated to the latest now. Will need to update all the nginx configurations to use the correct path now too.

**Pull request closed without merging**
